openapi: 3.0.0
info:
  title: Kapa-GPT Integration API
  description: API to handle sending queries from kapa.ai to a custom GPT instance and receiving responses.
  version: 1.0.0
paths:
  /sendToGPT:
    post:
      operationId: sendQueryToGPT
      summary: Sends a user's question to the custom GPT instance.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: Question fetched from kapa.ai.
                context:
                  type: string
                  description: Additional context or instructions for the GPT.
      responses:
        "200":
          description: Successfully sent the question and received a response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: Response from the custom GPT.
  /receiveFromGPT:
    post:
      operationId: receiveResponseFromGPT
      summary: Receives responses from the custom GPT and sends them back to kapa.ai.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                response:
                  type: string
                  description: Response generated by GPT to be sent back to kapa.ai.
      responses:
        "200":
          description: Response successfully received and processed.
