openapi: 3.0.0
info:
  title: Kapa-GPT Integration API
  description: API to handle sending queries from kapa.ai to a custom GPT instance and receiving responses.
  version: 1.0.0
servers:
  - url: https://chat.openai.com/g/g-LpF8CWevm-kapagpt-router
    description: Example server endpoint (update this with actual server URL when available)
paths:
  /sendToGPT:
    post:
      operationId: sendQueryToGPT
      summary: Sends a structured query to the custom GPT instance.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                messages:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        description: Role of the message (system, user, query, context).
                      content:
                        type: string
                        description: Content of the message based on its role.
                useRetrieval:
                  type: boolean
                  description: Whether to use retrieval-based answering.
                persistAnswers:
                  type: boolean
                  description: Whether to persist this conversation for future context.
      responses:
        "200":
          description: Successfully processed the query.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: Response from the custom GPT.
/receiveFromGPT:
  post:
    operationId: receiveResponseFromGPT
    summary: Receives responses from the custom GPT and sends them back to kapa.ai.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              response:
                type: string
                description: Response generated by GPT to be sent back to kapa.ai.
              metadata:
                type: object
                description: Optional metadata about the response.
    responses:
      "200":
        description: Response successfully received and processed.
      "400":
        description: Invalid response format or content.
      "500":
        description: Server error processing the response.
